version: '3.7'
services:
  postgres:
    image: postgres:12.3-alpine
    restart: always
    volumes:
      - torxebec_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "torxebec"
      POSTGRES_PASSWORD: "12345"
    ports:
      - 5434:5432
    networks:
      - torxebec_network

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python app/main.py
    restart: always
    tty: true
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    networks:
      - torxebec_network
    env_file:
      - .env

volumes:
  torxebec_data:

networks:
  torxebec_network:
    driver: bridge